[package]
name = "telepipe-core"
version = "0.3.0"
edition = "2021"
authors = ["G Six <g@teleplank.com>"]
description = "Core Telepipe implementation"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
